In [ ]:
import sys
import pandas as pd
import numpy as np
from pathlib import Path
from tqdm import tqdm

In [ ]:
# Define the root path
root = Path("path_to_chembl_data")  # Replace with the actual path to your ChEMBL data

# Files downloaded following instructions in README
csv_files = root.glob("*/joined_data_binarization/joined_all_max_activity.csv")
csv_files = list(csv_files)
csv_files = [str(f) for f in csv_files]

In [ ]:
len(csv_files)

318

In [ ]:
joined_df = pd.DataFrame()
for f in csv_files:
    df = pd.read_csv(f)
    df['species'] = str(f).split('/')[-3]
    joined_df = pd.concat([joined_df, df], ignore_index=True)
joined_df.shape

(427073, 3)

In [ ]:
joined_df.head()

,smiles,active,species
0,COc1cc2c(cc1OC)C[N+](Cc1cn(-c3ccc(C(C)(C)C)cc3...,0,acinetobacterbaylyi
1,COc1cc2c(cc1OCCCC(=O)Nc1cc(C(=O)Nc3ccc4oc(C(=O...,1,acinetobacterbaylyi
2,COc1cc2c(cc1OCCCC(=O)Nc1cc(C(=O)Nc3ccc4sc(C(=O...,1,acinetobacterbaylyi
3,C#CCO[C@@H]1[C@@H](C)[C@H](OC(=O)NCCCN=C(N)NC(...,0,acinetobactercalcoaceticus
4,C=C1CCOC2C(=O)N(Cc3ccccc3)[C@]1(O)C(=O)N2Cc1cc...,0,acinetobactercalcoaceticus

In [ ]:
joined_df.smiles.nunique()

186462

In [ ]:
joined_df[joined_df['active']==1].drop_duplicates().shape

(107774, 3)

In [ ]:
joined_df[joined_df['active']==1].smiles.nunique()

46066

In [ ]:
joined_df.drop_duplicates().shape

(427073, 3)

In [ ]:
matrix = joined_df[joined_df['active']==1].pivot(index='smiles', columns='species', values='active')

matrix = matrix.fillna(0).astype(int)
matrix

/tmp/ipykernel_1207675/1716291255.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  matrix = matrix.fillna(0).astype(int)

species,acinetobacterbaumannii,acinetobacterbaylyi,acinetobactercalcoaceticus,acinetobactercalcoaceticussubsp.anitratus,acinetobacterhaemolyticus,acinetobacterlwoffii,acinetobacterpittii,actinomycesisraelii,actinomycesnaeslundii,actinomycesviscosus,...,vibrioparahaemolyticus,vibriosplendidus,vibriovulnificus,xanthomonasaxonopodis,xanthomonascampestris,xanthomonasoryzae,xanthomonasvesicatoria,yersiniaenterocolitica,yersiniapestis,yersiniapseudotuberculosis
smiles,,,,,,,,,,,,,,,,,,,,,
BrC1[C@@H](c2c[nH]c3ccccc23)c2[nH]c3ccccc3c2[C@@H]1c1c[nH]c2ccccc12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
BrCCCCCOCc1c(-c2ccccc2)nc2sc3ccccc3n12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
BrCCCOCc1c(-c2ccccc2)nc2sc3ccccc3n12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Brc1c(-c2ccc(-c3[nH]c4cc(C5=NCCN5)ccc4c3Br)cc2)[nH]c2cc(C3=NCCN3)ccc12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Brc1c(-c2ccc3c(c2)OCO3)nc2ncccn12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
c1csc(Cc2nn3c(-c4[nH]nc5c4CCC5)nnc3s2)c1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
c1ncn(-c2ccc(COc3ccc(-n4cncn4)cc3)cc2)n1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
c1nnc(Nc2cncc(C3CCCN3)n2)s1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
c1nnc(Nc2cncc(C3CCCN3CC3CC3)n2)s1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
c1sc(C2CCCC2)nc1CN1CCn2c(nnc2C2CC2)C1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
matrix.shape # Only 273 species have at least one active

(46066, 273)

In [ ]:
matrix.sum().sum()

np.int64(107774)

In [ ]:
joined_df.columns

Index(['smiles', 'active', 'species'], dtype='object')

In [ ]:
joined_df.to_csv('../../data/figures_source_data/chembl_compound_species_activity_datapoints.csv', index=False)

In [ ]:
matrix.to_csv('../../data/figures_source_data/binary_activity_matrix_chembl.csv', index=True)